// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace XamChat.IOS
{
	public partial class FriendsController : UITableViewController
	{
		readonly FriendViewModel friendViewModel = ServiceContainer.Resolve<FriendViewModel>();

		public FriendsController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			TableView.Source = new TableSource();
		}

		public async override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);

			try
			{
				await friendViewModel.getFriends();

				TableView.ReloadData();
			}
			catch (Exception exc)
			{
				//exc.DisplayError();
			}
		}

		class TableSource : UITableViewSource
		{
			const string CellName = "FriendCell";
			readonly FriendViewModel friendViewModel = ServiceContainer.Resolve<FriendViewModel>();

			public override int RowsInSection(UITableView tableview, int section)
			{
				return friendViewModel.friendlist == null ? 0 : friendViewModel.friendlist.Length; 
			}

			public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
			{
				var friend = friendViewModel.friendlist [indexPath.Row];
				var cell = tableView.DequeueReusableCell(CellName);
				if (cell == null)
				{
					cell = new UITableViewCell(UITableViewCellStyle.Default, CellName);
					cell.AccessoryView = UIButton.FromType(UIButtonType.ContactAdd);
					cell.AccessoryView.UserInteractionEnabled = false;
				}
				cell.TextLabel.Text = friend.Username;
				return cell;
			}
		}
	}
}
