// This file has been autogenerated from a class added in the UI designer.
using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using XamChat;

namespace XamChat.IOS
{
	public partial class MyMessageCell : BaseMessageCell
	{
		public MyMessageCell (IntPtr handle) : base (handle)
		{
		}

		public override void Update(MessageM message)
		{
			this.message.Text = message.Text;
		}
	}
}
