#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamChat.Droid.Resource", IsApplication=true)]

namespace XamChat.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SlidingMenuSharp.Resource.Attribute.behindOffset = global::XamChat.Droid.Resource.Attribute.behindOffset;
			global::SlidingMenuSharp.Resource.Attribute.behindScrollScale = global::XamChat.Droid.Resource.Attribute.behindScrollScale;
			global::SlidingMenuSharp.Resource.Attribute.behindWidth = global::XamChat.Droid.Resource.Attribute.behindWidth;
			global::SlidingMenuSharp.Resource.Attribute.fadeDegree = global::XamChat.Droid.Resource.Attribute.fadeDegree;
			global::SlidingMenuSharp.Resource.Attribute.fadeEnabled = global::XamChat.Droid.Resource.Attribute.fadeEnabled;
			global::SlidingMenuSharp.Resource.Attribute.mode = global::XamChat.Droid.Resource.Attribute.mode;
			global::SlidingMenuSharp.Resource.Attribute.selectorDrawable = global::XamChat.Droid.Resource.Attribute.selectorDrawable;
			global::SlidingMenuSharp.Resource.Attribute.selectorEnabled = global::XamChat.Droid.Resource.Attribute.selectorEnabled;
			global::SlidingMenuSharp.Resource.Attribute.shadowDrawable = global::XamChat.Droid.Resource.Attribute.shadowDrawable;
			global::SlidingMenuSharp.Resource.Attribute.shadowWidth = global::XamChat.Droid.Resource.Attribute.shadowWidth;
			global::SlidingMenuSharp.Resource.Attribute.touchModeAbove = global::XamChat.Droid.Resource.Attribute.touchModeAbove;
			global::SlidingMenuSharp.Resource.Attribute.touchModeBehind = global::XamChat.Droid.Resource.Attribute.touchModeBehind;
			global::SlidingMenuSharp.Resource.Attribute.viewAbove = global::XamChat.Droid.Resource.Attribute.viewAbove;
			global::SlidingMenuSharp.Resource.Attribute.viewBehind = global::XamChat.Droid.Resource.Attribute.viewBehind;
			global::SlidingMenuSharp.Resource.Id.fullscreen = global::XamChat.Droid.Resource.Id.fullscreen;
			global::SlidingMenuSharp.Resource.Id.left = global::XamChat.Droid.Resource.Id.left;
			global::SlidingMenuSharp.Resource.Id.margin = global::XamChat.Droid.Resource.Id.margin;
			global::SlidingMenuSharp.Resource.Id.right = global::XamChat.Droid.Resource.Id.right;
			global::SlidingMenuSharp.Resource.Id.selected_view = global::XamChat.Droid.Resource.Id.selected_view;
			global::SlidingMenuSharp.Resource.Id.slidingmenumain = global::XamChat.Droid.Resource.Id.slidingmenumain;
			global::SlidingMenuSharp.Resource.Layout.slidingmenumain = global::XamChat.Droid.Resource.Layout.slidingmenumain;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu = global::XamChat.Droid.Resource.Styleable.SlidingMenu;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindOffset = global::XamChat.Droid.Resource.Styleable.SlidingMenu_behindOffset;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindScrollScale = global::XamChat.Droid.Resource.Styleable.SlidingMenu_behindScrollScale;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindWidth = global::XamChat.Droid.Resource.Styleable.SlidingMenu_behindWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeDegree = global::XamChat.Droid.Resource.Styleable.SlidingMenu_fadeDegree;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeEnabled = global::XamChat.Droid.Resource.Styleable.SlidingMenu_fadeEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_mode = global::XamChat.Droid.Resource.Styleable.SlidingMenu_mode;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorDrawable = global::XamChat.Droid.Resource.Styleable.SlidingMenu_selectorDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorEnabled = global::XamChat.Droid.Resource.Styleable.SlidingMenu_selectorEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowDrawable = global::XamChat.Droid.Resource.Styleable.SlidingMenu_shadowDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowWidth = global::XamChat.Droid.Resource.Styleable.SlidingMenu_shadowWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeAbove = global::XamChat.Droid.Resource.Styleable.SlidingMenu_touchModeAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeBehind = global::XamChat.Droid.Resource.Styleable.SlidingMenu_touchModeBehind;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewAbove = global::XamChat.Droid.Resource.Styleable.SlidingMenu_viewAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewBehind = global::XamChat.Droid.Resource.Styleable.SlidingMenu_viewBehind;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int color_names = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int behindOffset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int behindScrollScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int behindWidth = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int fadeDegree = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int fadeEnabled = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int mode = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int selectorDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int selectorEnabled = 2130771980;
			
			// aapt resource value: 0x7f010008
			public const int shadowDrawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int shadowWidth = 2130771977;
			
			// aapt resource value: 0x7f010006
			public const int touchModeAbove = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int touchModeBehind = 2130771975;
			
			// aapt resource value: 0x7f010001
			public const int viewAbove = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int viewBehind = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050004
			public const int black = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int blue = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int green = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int red = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int white = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060001
			public const int list_padding = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int shadow_width = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int slidingmenu_offset = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add139 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backicon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int comments16 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int customButton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int CustomCursor = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int group4 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int left207 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int monoandroidsplash = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int shadow = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0010
			public const int Txtview_Password = 2131361808;
			
			// aapt resource value: 0x7f0a000e
			public const int Txtview_Username = 2131361806;
			
			// aapt resource value: 0x7f0a0019
			public const int btn_add = 2131361817;
			
			// aapt resource value: 0x7f0a0016
			public const int btn_back = 2131361814;
			
			// aapt resource value: 0x7f0a0018
			public const int btn_friendlist = 2131361816;
			
			// aapt resource value: 0x7f0a0012
			public const int btn_login = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int btn_register = 2131361811;
			
			// aapt resource value: 0x7f0a000c
			public const int btn_send = 2131361804;
			
			// aapt resource value: 0x7f0a001a
			public const int conversation = 2131361818;
			
			// aapt resource value: 0x7f0a0011
			public const int editTxt_Password = 2131361809;
			
			// aapt resource value: 0x7f0a000f
			public const int editTxt_Username = 2131361807;
			
			// aapt resource value: 0x7f0a000b
			public const int editTxt_mess = 2131361803;
			
			// aapt resource value: 0x7f0a000a
			public const int form = 2131361802;
			
			// aapt resource value: 0x7f0a0003
			public const int fullscreen = 2131361795;
			
			// aapt resource value: 0x7f0a001c
			public const int help = 2131361820;
			
			// aapt resource value: 0x7f0a0005
			public const int imgv_avatar = 2131361797;
			
			// aapt resource value: 0x7f0a0001
			public const int left = 2131361793;
			
			// aapt resource value: 0x7f0a0006
			public const int list_item = 2131361798;
			
			// aapt resource value: 0x7f0a0009
			public const int lv_chat = 2131361801;
			
			// aapt resource value: 0x7f0a0007
			public const int lv_conversation = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int lv_friendlist = 2131361800;
			
			// aapt resource value: 0x7f0a000d
			public const int mainLogin = 2131361805;
			
			// aapt resource value: 0x7f0a0004
			public const int margin = 2131361796;
			
			// aapt resource value: 0x7f0a001b
			public const int new_game = 2131361819;
			
			// aapt resource value: 0x7f0a0002
			public const int right = 2131361794;
			
			// aapt resource value: 0x7f0a0000
			public const int selected_view = 2131361792;
			
			// aapt resource value: 0x7f0a0014
			public const int sendMsgLayout = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int slidingmenumain = 2131361813;
			
			// aapt resource value: 0x7f0a0017
			public const int text_title = 2131361815;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int num_cols = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Baseitem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChatMessageItemLeft = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChatMessageItemRight = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ConversationActivity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FriendListActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainActivity = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MessageActivity = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int slidingmenumain = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int menu_custom = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int MenuOption = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int Test = 2131427330;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080000
			public const int ApplicationName = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int ErrorTitle = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int Loading = 2131230722;
			
			// aapt resource value: 0x7f080019
			public const int about = 2131230745;
			
			// aapt resource value: 0x7f08001c
			public const int about_msg = 2131230748;
			
			// aapt resource value: 0x7f08000e
			public const int anim_fold = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int anim_scale = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int anim_slide = 2131230735;
			
			// aapt resource value: 0x7f08000c
			public const int anim_zoom = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int animations = 2131230731;
			
			// aapt resource value: 0x7f08001d
			public const int apache_license = 2131230749;
			
			// aapt resource value: 0x7f080003
			public const int app_name = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int attach = 2131230727;
			
			// aapt resource value: 0x7f080010
			public const int changing_fragments = 2131230736;
			
			// aapt resource value: 0x7f08001b
			public const int contact = 2131230747;
			
			// aapt resource value: 0x7f080005
			public const int general = 2131230725;
			
			// aapt resource value: 0x7f080015
			public const int github = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int github_label = 2131230742;
			
			// aapt resource value: 0x7f080012
			public const int left = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int left_and_right = 2131230740;
			
			// aapt resource value: 0x7f08001a
			public const int licenses = 2131230746;
			
			// aapt resource value: 0x7f08001e
			public const int no_email = 2131230750;
			
			// aapt resource value: 0x7f080004
			public const int properties = 2131230724;
			
			// aapt resource value: 0x7f080018
			public const int responsive_explanation = 2131230744;
			
			// aapt resource value: 0x7f080011
			public const int responsive_ui = 2131230737;
			
			// aapt resource value: 0x7f080013
			public const int right = 2131230739;
			
			// aapt resource value: 0x7f080008
			public const int title_bar = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int title_bar_content = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int title_bar_slide = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int viewpager = 2131230726;
			
			// aapt resource value: 0x7f080017
			public const int what_is_this = 2131230743;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int ExampleTheme = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int Mono_Android_Theme_Splash = 2131296257;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SlidingMenu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 3
			public const int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public const int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public const int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 11
			public const int SlidingMenu_fadeDegree = 11;
			
			// aapt resource value: 10
			public const int SlidingMenu_fadeEnabled = 10;
			
			// aapt resource value: 0
			public const int SlidingMenu_mode = 0;
			
			// aapt resource value: 13
			public const int SlidingMenu_selectorDrawable = 13;
			
			// aapt resource value: 12
			public const int SlidingMenu_selectorEnabled = 12;
			
			// aapt resource value: 8
			public const int SlidingMenu_shadowDrawable = 8;
			
			// aapt resource value: 9
			public const int SlidingMenu_shadowWidth = 9;
			
			// aapt resource value: 6
			public const int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 7
			public const int SlidingMenu_touchModeBehind = 7;
			
			// aapt resource value: 1
			public const int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public const int SlidingMenu_viewBehind = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
